import {
  Loader2,
  HeartHandshake,
  Heart,
  Globe,
  ShieldCheck,
  Stethoscope,
  Users,
  Search,
  Star,
  CheckCircle2,
  Clock,
  MapPin,
  MessageSquareHeart,
  Sparkles,
  ArrowRight,
  Menu,
  X,
  Sun,
  Moon,
  Phone,
  Mail,
  Instagram,
  Facebook,
  Linkedin,
  Calendar,
  CreditCard,
  BellRing,
  BadgeCheck,
  GraduationCap,
  HandHeart,
  type LucideProps,
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  logo: HeartHandshake,
  heart: Heart,
  google: Globe,
  shield: ShieldCheck,
  stethoscope: Stethoscope,
  users: Users,
  search: Search,
  star: Star,
  check: CheckCircle2,
  clock: Clock,
  pin: MapPin,
  chat: MessageSquareHeart,
  sparkles: Sparkles,
  arrowRight: ArrowRight,
  menu: Menu,
  close: X,
  sun: Sun,
  moon: Moon,
  phone: Phone,
  mail: Mail,
  instagram: Instagram,
  facebook: Facebook,
  linkedin: Linkedin,
  calendar: Calendar,
  card: CreditCard,
  bell: BellRing,
  verified: BadgeCheck,
  graduation: GraduationCap,
  handHeart: HandHeart,
}

export type IconKey = keyof typeof Icons
export type Icon = (props: LucideProps) => JSX.Element
